
// Summaries of the original event narratives; numerical outcomes stay in each variant.
export const eventFamilyDescriptions: Record<string, string> = {
 "defeat": "Agent 在战斗中落败并死亡。按对手和攻守身份显示对应结算；死亡由战斗代码处理，事件选项列出额外效果。",
 "victory": "Agent 在战斗中获胜。对手类型、攻守身份及败方死亡或撤退决定结算分支；选项可能进一步改变 Profile、Menace 或人物特质。",
 "retreat from combat": "主动发起战斗的 Agent 败退，保住性命后结算这次战斗带来的影响。",
 "fled from combat": "受到攻击的 Agent 在致命一击前逃离，按对手显示对应的撤退结算。",
 "mourning": "人物因亲友死亡而哀悼。不同反应可能改变 Sanity、Shadow、偏好、人物关系及哀悼持续时间；部分分支允许玩家花费资源干预。",
 "%holy_order": "Agent 接触当地 Witch Coven 的仪式与活动。不同遭遇提供影响教团或周边英雄态度的机会。",
 "the alchemists": "Agent 发现一群追逐炼金术成果的人，可以引导他们的研究来换取利益，或将成果用于传播 Shadow。",
 "sandstorm": "沙暴阻碍 Agent 的行动。可以等待、借助神力或采取其他应对方式，不同变体的任务损失与受伤风险不同。",
 "merchant of antiquities": "古董商察觉 Agent 的隐秘活动，以泄露消息相要挟。可以购买不同档次的货物，或承受拒绝交易的后果。",
 "abyssal horror": "人物发现亲族已转化为 Deep One，恐惧使其对 Deep Ones 产生敌意，部分遭遇还会损害 Sanity。",
 "family falling to shadow": "亲族受到 Shadow 侵蚀，引发担忧、抗拒或共同堕落。双方 Shadow、人物身份与亲属关系决定可触发的反应。",
 "guilt in the family": "亲族的罪行与高 Menace 引发家人的质问、包庇或谴责，影响双方关系，并可能带来掩护或 Sanity 损失。",
 "exploring ruins at %location_name": "Agent 探索尚未指定特殊路线的遗迹，在金钱、隐秘发现与危险之间作出选择。各遭遇使用相同探索入口，但奖励、风险和抽选权重分别结算。",
 "in the dark": "统治者听闻 Chosen One 对古神威胁的警告，向 Agent 询问传闻是否属实。不同神祇与人物状态对应不同谈话和选择。",
 "watched": "城中老妇组成的闲谈网络开始怀疑 Agent 的行踪，迫使其应对监视和流言。",
 "the orcish toast": "Agent 被邀请参加 Orc 的 Grott 敬酒。人类或 The Cursed 与 The Warlord 使用不同分支，饮酒和拒绝的效果分别列出。",
 "inn between places": "负伤的 Agent 在荒野发现旅店，可以花钱休整；地形决定旅店场景及相应的触发条件。",
 "a light in the dark": "地下的 Light Lady 驱散黑暗并阻碍 Agent，相关遭遇提供应对这一威胁的选择。",
 "fresh-slain quarry": "Agent 杀死 Great Stag 后处理其遗体。受污染与未受污染的 Great Stag 使用不同结算，死亡代码已先处理对应的 Shadow 或经验奖励。",
 "plundering shipwreck at %location_name": "Agent 完成 Plunder Shipwreck 后搜寻船骸中的财物，抽到的遭遇决定可选奖励与风险。",
 "exploring shipwreck at %location_name": "Agent 深入船骸探索，不同遭遇分别处理其中的发现、危险与可带走的物品。",
 "effect of orc grott wares off.": "Orc Grott 的效果到期时，携带装满的 Drinking Horn 的 Agent 可以决定是否再次饮用；Orc 与其他种族使用不同分支。",
 "the audacity!": "醉酒贵族当众说出与 Agent 合谋夺权的打算，Agent 必须处理这场险些暴露阴谋的失言。",
 "a confession": "Agent 在告解室说错暗号，被限制撒谎的魔法卷入一场意外告解；The Redeemer 与其他 Agent 的应对选项不同。",
 "helping hands": "Agent 在任务中结识一群愿意效力的流氓，可以利用他们提供的帮助；各变体有自己的冷却条件与结果。",
 "on the hunt": "追踪 Manticore 或 Ogre 时发现新鲜踪迹，Agent 可以决定是否牺牲休息来加快追猎。",
 "opportunity cost": "Agent 获得以暂时牺牲任务对应属性来换取当前进展的机会，Might、Lore、Intrigue、Command 任务分别使用各自的分支。",
 "potential benefactor": "潜在资助者要求先处理当地的 Unrest 或 Plague，Agent 可以选择解决问题来争取支持，或采用其他方式应对。",
 "slow learning": "Agent 向谨慎的施法者学习，希望跳过缓慢而安全的教学。聚居地、回合阶段与选择共同影响获得的进展和代价。",
 "the turncoat and the hidden path": "带路人指出隐秘通道后再次索要封口费，Agent 可以付款、退让或设法利用这条通路。",
 "witness in the field": "Agent 为行动训练和部署打手时遭遇泄密风险。寒冷与非寒冷地区使用不同的任务与地形条件。",
 "weird dreams iii": "Agent 在梦中将白天的研究或调查联系起来，醒后获得任务进展；Lore 与 Intrigue 任务的奖励不同。",
 "the hard times": "受灾聚居地的祭司向 Agent 请求援助。Ophanim 与其他神祇的分支分别处理捐款、当地危机和 Faith。",
 "%ruler_name's last drink": "宫廷密谋通过毒酒除掉令人厌恶的统治者。Agent 参与的交涉与统治者自身触发的事件提供不同选择。",
 "a glimpse of the greater things": "Agent 在梦中接触古神的异象，醒后可能受到惊扰或获得启示。五种异象共用同一组可触发神祇条件，再由事件池抽选。"
};
