import type { EventRecord } from "./EventTypes";

// Names summarize source conditions, narrative or options; not event IDs.
const labels: Readonly<Record<string, string>> = {
  "anw.midwitch_dark": "信仰渊源分支",
  "anw.midwitch_fluidic": "光暗平衡分支",
  "anw.midwitch_hat": "医药与流放分支",
  "anw.mid_alchemist": "默认分支",
  "fog.midch_alchemists": "Human 分支",
  "anw.mid_trader": "默认分支",
  "fog.midch_merchant_of_antiquities": "Human 分支",
  "anw.mid_sandstorm": "Desert / Dry 分支",
  "fog.midch_sandstorm": "扩展地形分支",
  "anw.p2pdeepOne": "Call of the Abyss 英雄分支",
  "anw.p2pdeepOne2": "海边亲属相遇分支",
  "anw.mourning_test": "内疚自责分支",
  "anw.mourning_10": "死亡恐惧分支",
  "anw.mid_oldwomen": "默认分支",
  "fog.midch_watched": "非 The Harvester 分支",
  "fog.midch_orcish_toast_human": "Human / The Cursed 分支",
  "fog.midch_orcish_toast_warlord": "The Warlord 分支",
  "fog.unit_inn_between_deserts": "干旱地形分支",
  "fog.unit_inn_between_grass": "草原与高地分支",
  "fog.unit_inn_between_snowy": "寒冷地形分支",
  "fog.unit_inn_between_swamp": "Swamp 分支",
  "anw.mid_lightLady1": "统治者与 Ward 分支",
  "anw.mid_lightLady2": "默认分支",
  "nature.nature_dead_stag_dark": "受污染的 Great Stag 分支",
  "nature.nature_dead_stag_light": "未受污染的 Great Stag 分支",
  "OrcsPlus.drinkGrott": "非 Orc 分支",
  "OrcsPlus.drinkGrott_Orc": "Orc 分支",
  "maeRedux.midchP2P_confession": "普通 Agent 分支",
  "maeRedux.midchP2P_confession_redeemer": "The Redeemer 分支",
  "maeRedux.midch_hunting_Manticore": "Defeat Manticore 分支",
  "maeRedux.midch_hunting_Ogre": "Defeat Ogre 分支",
  "maeRedux.mid_potentialbenefactor_1": "Unrest 分支",
  "maeRedux.mid_potentialbenefactor_2": "Plague 分支",
  "maeRedux.midch_village_field_witness": "非寒冷地形分支",
  "maeRedux.midch_village_field_witness_snow": "寒冷地形分支",
  "maeRedux.mid_weirddreams_3": "Lore 分支",
  "maeRedux.mid_weirddreams_3_intrigue": "Intrigue 分支",
  "maeRedux.move_ophanim_village_hard_times": "Ophanim 分支",
  "maeRedux.move_village_hard_times": "默认分支",
  "maeRedux.P2P_MIDCH_ruler_cruel_a_goblet_of_poison": "Agent 介入分支",
  "maeRedux.PERSON_ruler_cruel_a_goblet_of_poison": "统治者状态分支",
  "anw.fallingIntoShadow1": "精神压力分支",
  "anw.fallingIntoShadow2": "抗拒 Shadow分支",
  "anw.fallingIntoShadow3": "分担 Shadow分支",
  "anw.fallingIntoShadow4": "亲属侵蚀分支",
  "anw.fallingIntoShadow5": "警惕 Shadow分支",
  "anw.fallingIntoShadow6": "恐惧反噬分支",
  "anw.highMenace1": "亲属劝阻分支",
  "anw.highMenace2": "亲属敌视分支",
  "anw.highMenace3": "声誉辩护分支",
  "anw.highMenace4": "贿赂守卫分支",
  "anw.highMenace5": "忠诚冲突分支",
  "anw.mourning_2": "绝望侵蚀分支",
  "anw.mourning_3": "追忆死者分支",
  "anw.mourning_4": "清除 Shadow分支",
  "anw.mourning_5": "相互慰藉分支",
  "anw.mourning_6": "亡者阴影分支",
  "anw.mourning_7": "忽视职责分支",
  "anw.mourning_8": "追悼仪式分支",
  "anw.mourning_9": "质疑信仰分支",
  "anw.exploreRuins_Generic1": "藏金线索分支",
  "anw.exploreRuins_Generic2": "危险通道分支",
  "anw.exploreRuins_Generic3": "远古神器分支",
  "anw.exploreRuins_Generic4": "金属丝陷阱分支",
  "anw.exploreRuins_Generic5": "异变洞穴分支",
  "anw.exploreRuins_Generic6": "共同探索者分支",
  "anw.exploreRuins_Generic7": "地下宝库分支",
  "CLib.plunderWreck_Generic1": "军官钱箱分支",
  "CLib.plunderWreck_Generic2": "坍塌宝箱分支",
  "ComLib.plunderWreck_Generic3": "海底神器分支",
  "CLib.plunderWreck_Generic4": "古老陶罐分支",
  "CLib.plunderWreck_Generic5": "囚笼亡灵分支",
  "CLib.plunderWreck_Generic6": "竞争打捞者分支",
  "CLib_plunderWreck_Generic7": "海底宝藏分支",
  "maeRedux.midch_helpinghands_1": "魔法物品分支",
  "maeRedux.midch_helpinghands_2": "盗窃与煽动分支",
  "maeRedux.midch_helpinghands_3": "装备与陷阱分支",
  "fog.midchP2P_in_the_dark_generic": "默认分支",
  "fog.midchP2P_in_the_dark_iastur": "Iastur 分支",
  "fog.midchP2P_in_the_dark_mammon": "Mammon 分支",
  "fog.midchP2P_in_the_dark_ophanim": "Ophanim 分支",
  "fog.midchP2P_in_the_dark_swwf": "She Who Will Feast 分支",
  "fog.midchP2P_in_the_dark_vinerva": "Vinerva 分支",
  "maeRedux.midch_Opportunity_COMMAND": "Command 分支",
  "maeRedux.midch_Opportunity_INTRIGUE": "Intrigue 分支",
  "maeRedux.midch_Opportunity_LORE": "Lore 分支",
  "maeRedux.midch_Opportunity_MIGHT": "Might 分支",
  "maeRedux.mid_audacious_t1": "200 回合前分支",
  "maeRedux.mid_turncoatnoble_t1": "200 回合前分支",
  "maeRedux.slowlearning_2_T1": "聚居地 · 200 回合前分支",
  "maeRedux.slowlearning_1_t1": "野外 · 151–199 回合分支",
  "maeRedux.mid_audacious_t2": "151–399 回合分支",
  "maeRedux.mid_turncoatnoble_t2": "151–399 回合分支",
  "maeRedux.slowlearning_2_T2": "聚居地 · 151–399 回合分支",
  "maeRedux.slowlearning_1_t2": "野外 · 151–399 回合分支",
  "maeRedux.mid_audacious_t3": "376 回合起分支",
  "maeRedux.mid_turncoatnoble_t3": "376 回合起分支",
  "maeRedux.slowlearning_2_T3": "聚居地 · 376 回合起分支",
  "maeRedux.slowlearning_1_t3": "野外 · 376 回合起分支",
  "maeRedux.god_dream_iastur": "Iastur 梦境分支",
  "maeRedux.god_dream_mammon": "Mammon 梦境分支",
  "maeRedux.god_dream_ophanim": "Ophanim 梦境分支",
  "maeRedux.god_dream_snake": "She Who Will Feast 梦境分支",
  "maeRedux.god_dream_vinerva": "Vinerva 梦境分支"
};

export function variantLabel(record: EventRecord, _index?: number) {
 if (labels[record.eventId]) return labels[record.eventId];
 const combat = /^与(.+?)战斗，Agent 作为(进攻者|防守者)，(获胜|战败)，败方(死亡|撤退)时显示。$/.exec(record.decision.trigger);
 if (combat) return combat[1].trim() + " · " + combat[2] + " · " + (combat[3] === "获胜" ? "对手" : "Agent ") + combat[4];
 const depth = /遗迹已探索深度 = (\d+)/.exec(record.decision.condition);
 return depth ? "探索深度 " + depth[1] + " 分支" : "特殊分支";
}
