"use client";

import Image from "next/image";
import { useRef, useState, type ReactNode } from "react";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { ChevronDown, CircleDot, Eye, PanelLeftClose, PanelLeftOpen, Shield } from "lucide-react";
import MobileReferenceDialog from "./MobileReferenceDialog";
import { GodMark } from "../components/GodMark";

gsap.registerPlugin(ScrollTrigger, useGSAP);
type GodChoice = "index" | "she-who-will-feast" | "iastur" | "vinerva" | "cordyceps" | "kishi" | "living-void" | "chandalor";
type Relation = { name: string; href: string; meta?: string; text?: string; image?: string };
type DetailItem = { name: string; text: string; image?: string; seal?: number; meta?: string; statLine?: string; location?: string; preferenceText?: string; id?: string; baseGame?: boolean };

const seals = [
  { seal: 0, turn: 0, agents: 2, reward: "Heart of the Forest、Grove of Golden Roses" },
  { seal: 1, turn: 12, agents: 2, reward: "Grove of Salvation、Black Forest" },
  { seal: 2, turn: 24, agents: 3, reward: "Grove of Nectar、Grove of Peace Lillies" },
  { seal: 3, turn: 44, agents: 3, reward: "Choking Spores、Grove of Leper's Succor" },
  { seal: 4, turn: 72, agents: 4, reward: "Grove of Dragonflower" },
  { seal: 5, turn: 110, agents: 4, reward: "Neurotoxins、Pheromones" },
  { seal: 6, turn: 150, agents: 4, reward: "Serpentine Vines" },
  { seal: 7, turn: 200, agents: 5, reward: "Manifestation" },
  { seal: 8, turn: 300, agents: 5, reward: "" },
  { seal: 9, turn: 420, agents: 5, reward: "Wilderness Spirits、苏醒" },
];
const powers = [
  { seal: 0, name: "Heart of the Forest", cost: "动态", icon: "heart-of-forest.png", effect: "在土地上建立一个 Heart of the Forest。第一次施放消耗 0；之后按已使用次数逐步增加，公式为 min(4, max(1, floor(使用次数 ÷ 2)))。它既是 Vinerva 的据点，也是所有其他神力的施放中心。若执行者携带 Vinerva Seed，施放时会消耗种子并在新地点建立据点。", limit: "必须施放在陆地；没有已有据点时可任意选址，之后需要位于现有 Heart of the Forest 的 3 格范围内，或由携带种子的 Agent 把网络延伸到新地点。" },
  { seal: 0, name: "Grove of Golden Roses", cost: 1, icon: "grove-golden-roses.png", effect: "在聚居地建立 Temptation of Gold。当地统治者会得到一个可以把死刑犯或债务人换成财富的行动；执行后统治者获得 75 Gold，同时地点获得 25 Lingering Resentment，并把 Vinerva's Gift 增加 50。花园强度减少 50。", limit: "只能放在人类聚居地，且该地不能已有同名 Grove；目标必须处于任一 Heart of the Forest 的 3 格范围内。" },
  { seal: 1, name: "Grove of Salvation", cost: 2, icon: "grove-salvation.png", effect: "在地点留下 Temptation of Salvation。英雄可执行 Gift of Salvation，把自己的 Shadow 降低一半，但损失 8 Sanity；任务的吸引力会随自身 Shadow 增加，却会被 Awareness 与世界恐慌压低。", limit: "只能施放在 Heart of the Forest 3 格内的陆地。" },
  { seal: 1, name: "Black Forest", cost: 0, icon: "heart-of-forest.png", effect: "把带有 Vinerva's Gift 的统治者 Shadow 提高同等数量，并以 100% Shadow 为上限；消耗对应的 Gift。每次使用还会给最近的 Heart of the Forest 增加 15 Menace。", limit: "目标必须是有统治者的人类聚居地，地点带有 Vinerva's Gift，且统治者 Shadow 尚未达到 100%；Gift 必须位于 Heart 的 3 格范围内。" },
  { seal: 2, name: "Grove of Nectar", cost: 1, icon: "grove-nectar.png", effect: "建立 Temptation of Nectar。统治者可让当地 Gift of Nectar 生效：把饥荒降到 1%，并使食物产出提高 200%（总计为原来的 3 倍，另加 50 平坦食物）；代价是 Vinerva's Gift 增加 125，花园强度减少 50。", limit: "只能放在人类聚居地，且不能已有同名 Grove；目标须在 Heart 的 3 格范围内。" },
  { seal: 2, name: "Grove of Peace Lillies", cost: 2, icon: "grove-peace-lillies.png", effect: "建立 Temptation of Peace。统治者可让当地 Unrest 降到 1，并获得短期的安抚效果；代价是 Vinerva's Gift 增加 75，花园强度减少 25。", limit: "只能放在人类聚居地，且不能已有同名 Grove；目标须在 Heart 的 3 格范围内。" },
  { seal: 3, name: "Choking Spores", cost: 3, icon: "choking-spores.png", effect: "在目标聚居地及其周围地点放置 Choking Spores。每个地点的 Prosperity 降低 25%，从而连带降低金钱和军事产出；不消耗 Vinerva's Gift，但会给最近 Heart 增加 15 Menace。", limit: "目标必须有至少 50 点 Vinerva's Gift，位于 Heart 的 3 格范围内，且目标没有已有 Choking Spores。" },
  { seal: 3, name: "Grove of Leper's Succor", cost: 2, icon: "grove-lepers-succor.png", effect: "建立 Temptation of Health。统治者可把地点 Plague 降到 1；代价是 Vinerva's Gift 增加 45，花园强度减少 50。", limit: "只能放在人类聚居地，且不能已有同名 Grove；目标须在 Heart 的 3 格范围内。" },
  { seal: 4, name: "Grove of Dragonflower", cost: 1, icon: "grove-dragonflower.png", effect: "建立 Temptation of Might。英雄可执行 Gift of Might，获得 Vinerva's Gift of Might：第一次食用在 22 回合内提供 +4 Might，重复食用会刷新持续时间并提高等级，增益会逐级衰减；没有剩余增益时特质会变成 −1 Might，并持续制造成瘾倾向。", limit: "可施放在 Heart 的 3 格范围内的任意陆地。" },
  { seal: 5, name: "Neurotoxins", cost: 1, icon: "neurotoxins.png", effect: "把 Vinerva's Gift 转化为 Madness：每消耗 1 点 Gift 增加 2 点 Madness，最多把地点推到 300 Madness；消耗掉的 Gift 不会恢复。每次施放给最近 Heart 增加 15 Menace。", limit: "只能对 Heart 的 3 格范围内、带有 Vinerva's Gift 的人类聚居地施放。" },
  { seal: 5, name: "Pheromones", cost: 3, icon: "pheromones.png", effect: "在土地上生成 100 点 Tempting Pheromones。它每回合衰减 3；在强度 100 时，让当地所有 Vinerva 礼物的接受动机额外提高 25，可通过重复施放叠加。", limit: "必须在 Heart 的 3 格范围内施放在陆地上。" },
  { seal: 6, name: "Serpentine Vines", cost: 3, icon: "serpentine-vines.png", effect: "把目标地点所有英雄任务和中立挑战的 危险分别设为 8；每项任务独立记录这个危险值。施放后最近 Heart 增加 10 Menace。", limit: "必须在 Heart 的 3 格范围内；可以对任意地点施放。" },
  { seal: 7, name: "Manifestation", cost: 1, icon: "manifestation.png", effect: "让一个已经被 Vinerva's Gift 充分侵蚀的聚居地转化为 Manifestation，摧毁原有人类 settlement，并额外计入 Vinerva 的胜利分。新地点会带有一个 Heart of the Forest，随后逐渐把周边地块变成森林。", limit: "只能选择 Heart 的 3 格范围内、拥有至少 125 点 Vinerva's Gift 的人类聚居地。" },
  { seal: 9, name: "Wilderness Spirits", cost: 3, icon: "wilderness-spirits.png", effect: "在空地点生成一支 50 HP、不可控制的 Wilderness Spirits 军队。它会主动寻找附近 Shadow 低于 50% 的人类聚居地并夷平，经过的领地每回合有 25% 概率转为森林；最近 Heart 增加 30 Menace。", limit: "必须在 Heart 的 3 格范围内的空地点施放。" },
];

const traits: DetailItem[] = [{ name: "Vinerva's Gift of Might", image: "grove-dragonflower.png", text: "英雄食用 Dragonflower 后获得的成瘾特质，最多 5 级。每次食用在 22 回合内提供递减的 Might：第 1 级 +4，随后为 +3、+2、+2、+1、+1；持续时间耗尽后改为 −1 Might。再次食用会刷新 22 回合并提高等级，因此它同时是短期战斗强化和会把英雄反复吸回花园的长期牵引。" }];
const locationModifiers: DetailItem[] = [
  { name: "Vinerva's Gift", image: "gift.png", text: "统治者接受任一 Grove 的好处后留下的地点修正，初始强度由礼物决定：Gold +50、Nectar +125、Peace +75、Health +45。强度最高 300；它既是 Manifestation 与 Neurotoxins 的燃料，也会被 Black Forest 等神力消耗。地点会提供 Cultivate Her Gifts 宗教任务，且修正本身不会触发普通地点危机。" },
  { name: "Temptation of Gold", image: "grove-golden-roses.png", text: "Golden Roses 留下的地点修正，给统治者提供 Harvest for Gold 行动。行动会让统治者获得财富，却制造 25 Lingering Resentment，并把 Vinerva's Gift 增加 50；花园强度减少 50。" },
  { name: "Temptation of Salvation", image: "grove-salvation.png", text: "黄色花朵留下的地点修正，为英雄提供 Gift of Salvation。它能把执行者 Shadow 减半，但会造成 8 Sanity 伤害；Chosen One 不能执行。" },
  { name: "Temptation of Nectar", image: "grove-nectar.png", text: "Nectar Grove 留下的地点修正，为统治者提供 Harvest Nectar 行动。行动把饥荒压到 1%，提高食物产出并增加 Vinerva's Gift。" },
  { name: "Temptation of Peace", image: "grove-peace-lillies.png", text: "Peace Lily 留下的地点修正，为统治者提供 Drink Peace Lily 行动，把 Unrest 压到 1，并增加 Vinerva's Gift。" },
  { name: "Temptation of Health", image: "grove-lepers-succor.png", text: "Leper's Succor 留下的地点修正，为统治者提供 Use Leper's Succor 行动，把 Plague 压到 1，并增加 Vinerva's Gift。" },
  { name: "Temptation of Might", image: "grove-dragonflower.png", text: "Dragonflower 留下的地点修正，为英雄提供 Gift of Might；反复食用会提高 Vinerva's Gift of Might 的等级并形成依赖。" },
  { name: "Tempting Pheromones", image: "pheromones.png", text: "Pheromones 神力产生的地点修正，每回合衰减 3。它不是直接效果，而是提高当地所有 Vinerva 礼物的接受动机，100 点强度时额外提供 25 点动机，并可以叠加。" },
  { name: "Lingering Resentment", baseGame: true, text: "本体地点修正。统治者用 Golden Roses 换取财富后留下，每回合给地点增加 2 Unrest；若启用统治者特质影响修正，则 Intrigue 越高，减缓效果越明显。它可以触发普通地点危机。" },
  { name: "Choking Spores", id: "choking-spores-modifier", image: "choking-spores.png", text: "Choking Spores 神力在目标及相邻地点放置的毒雾修正，每回合缓慢衰减。它把 Prosperity 降低 25%，因此同时压低当地经济和军事能力，但不会直接杀伤人口。" },
  { name: "Gift of Nectar", image: "grove-nectar.png", text: "统治者接受 Nectar 后留下的短期地点修正：食物产出提高 200%，并额外提供 50 平坦食物；每回合影响值 −1.25，和 Vinerva's Gift 一样不触发普通危机。" },
];
const locations: DetailItem[] = [
  { name: "Heart of the Forest", id: "heart-location", image: "heart-location.png", text: "Vinerva 的核心据点。它允许使用半径 3 格内的专属神力，自身防御加成 50；地点可被人类国家派军队摧毁，并带有 Harvest Seed 挑战。每个 Heart 的存在都连接着同一个全球根系网络。" },
  { name: "Manifestation", id: "manifestation-location", image: "manifestation-location.png", seal: 7, text: "Manifestation 取代被献祭的人类聚居地，不再属于人类阵营。它每回合向周围传播森林地形，并自带新的 Heart of the Forest，因而可以把一次礼物转化为新的扩张节点。" },
];
const items: DetailItem[] = [{ name: "Vinerva Seed", image: "seed.png", text: "Harvest Seed 挑战的产物。携带它的 Agent 可以把 Heart of the Forest 神力带到新的地点；施放成功后种子被消耗，并在新地点建立 Heart。它是突破现有根系 3 格范围、重新铺开网络的主要方式。" }];
const specialUnits: DetailItem[] = [{ name: "Wilderness Spirit", image: "wilderness-spirits.png", seal: 9, text: "Wilderness Spirits 生成的不可控制游荡军队，初始 50 HP，不会自行解散。它优先攻击最近、Shadow 低于 50% 的人类聚居地；到达后执行无视和平的夷平，并在每回合把自己所在领地的一部分改成森林。" }];
const challenges: DetailItem[] = [{ name: "Harvest Seed", image: "seed.png", location: "Heart of the Forest。", meta: "Other", statLine: "Complexity: 1　Profile: 20　Menace: 0　XP: 3", text: "在 Heart of the Forest 收获一枚 Vinerva Seed。任务没有额外限制，完成后把种子放入执行者的物品栏；执行者有空物品槽时会更愿意选择它。" }];
const heroTasks: DetailItem[] = [
  { name: "Gift of Salvation", image: "grove-salvation.png", location: "Grove of Salvation。", meta: "Other", statLine: "Complexity: 1　Profile: 30　Menace: 0　XP: 3", preferenceText: "带有 Shadow 负面标签：厌恶 Shadow、Shadow 较高且 Awareness 较低的英雄更愿意执行；世界恐慌越高，任务越不吸引人。Tempting Pheromones 会提高接受动机。", text: "英雄把自身 Shadow 降低一半，但付出 8 Sanity。Chosen One 不能执行。" },
  { name: "Gift of Might", image: "grove-dragonflower.png", location: "Grove of Dragonflower。", meta: "Other", statLine: "Complexity: 1　Profile: 40　Menace: 0　XP: 3", preferenceText: "带有 Combat 与 Ambition 正面标签，同时带有危险物质的基础反对值；寻找危险敌人的英雄、已经成瘾的英雄和受 Pheromones 影响者更可能执行，Awareness 会降低意愿。", text: "英雄获得或升级 Vinerva's Gift of Might。重复执行会延长当前增益并提高成瘾等级，Chosen One 不能执行。" },
];
const rulerActions: DetailItem[] = [
  { name: "Harvest for Gold", image: "grove-golden-roses.png", location: "有 Temptation of Gold 的地点。", meta: "统治者行动", text: "在 Temptation of Gold 上执行：统治者获得 75 Gold，地点新增 25 Lingering Resentment，并让 Vinerva's Gift 增加 50；Golden Roses 的强度减少 50。" },
  { name: "Harvest Nectar", image: "grove-nectar.png", location: "有 Temptation of Nectar 的地点。", meta: "统治者行动", text: "在 Temptation of Nectar 上执行：把当地饥荒降到 1%，临时让食物产出提高 200%并增加 50 平坦食物，Vinerva's Gift 增加 125，Nectar 强度减少 50。" },
  { name: "Drink Peace Lily", image: "grove-peace-lillies.png", location: "有 Temptation of Peace 的地点。", meta: "统治者行动", text: "在 Temptation of Peace 上执行：把当地 Unrest 降到 1，Vinerva's Gift 增加 75，Peace Lily 强度减少 25。它只是短期平息，不会消除长期政治后果。" },
  { name: "Use Leper's Succor", image: "grove-lepers-succor.png", location: "有 Temptation of Health 的地点。", meta: "统治者行动", text: "在 Temptation of Health 上执行：把当地 Plague 降到 1，Vinerva's Gift 增加 45，Leper's Succor 强度减少 50。" },
];
const religion: DetailItem[] = [{ name: "A Darker Nature", image: "heart-of-forest.png", meta: "Witches 专属教义", text: "Vinerva 在场时，Witches Holy Order 会额外获得 A Darker Nature。它最多向 Elder 侧发展到 0、向人类侧发展到 −2；状态越负，Cultivate Her Gifts 的收益越高。教义让女巫把 Vinerva's Gift 变成持续增长的燃料。" }];
const religiousTasks: DetailItem[] = [{ name: "Holy: Cultivate Her Gifts", image: "manifestation.png", location: "有 Vinerva's Gift 的地点，并且有对应 Witches Holy Order。", meta: "Lore", statLine: "Complexity: 30　Profile: 40　Menace: 0　XP: 49", preferenceText: "任务带 Religion 标签；只有 Witches Holy Order 成员、且 A Darker Nature 不处于中立状态时可执行。", text: "在有 Vinerva's Gift 的地点进行 20 回合的培养。完成后按教义等级让 Gift 每回合额外增加 1%×等级，持续 20 回合；一次只能有一个培养任务。" }];
const events: DetailItem[] = [{ name: "Vinerva Gift Accepted", image: "gift.png", text: "统治者第一次接受任一 Vinerva 礼物时弹出的本体事件。它只负责提示地点已经留下 Vinerva's Gift，真正的数值变化由相应的统治者行动完成。" }];
const collections = [traits, locationModifiers, locations, items, specialUnits, challenges, heroTasks, rulerActions, religion, religiousTasks, events];
const allDetails = collections.flat();
function disambiguateDetailIds(items: Array<{ name: string; id?: string }>, reserved: string[]) {
 const seen = new Map<string, number>();
 reserved.forEach(name => seen.set(anchorFor(name), 1));
 items.forEach(item => { const base = item.id ? "entry-" + item.id : anchorFor(item.name); const count = seen.get(base) ?? 0; if (count > 0 && !item.id) item.id = base.replace(/^entry-/, "") + "-" + (count + 1); seen.set(base, count + 1); });
}
disambiguateDetailIds(allDetails, powers.map(item => item.name));
const referenceNames = Array.from(new Set([...powers.map((x) => x.name), ...allDetails.map((x) => x.name)])).sort((a, b) => b.length - a.length);
function anchorFor(name: string) { return `entry-${name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`; }
function refFor(name: string) { const p = powers.find((x) => x.name === name); if (p) return { name, image: p.icon, meta: `封印 ${p.seal} · 消耗 ${p.cost}`, text: p.effect, href: `#${anchorFor(name)}` }; const d = allDetails.find((x) => x.name === name); if (!d) return null; return { name, image: d.image, meta: d.meta ?? (d.seal !== undefined ? `封印 ${d.seal}` : "机制说明"), text: d.text, href: `#${d.id ? `entry-${d.id}` : anchorFor(name)}` }; }
function CrossReference({ name, href, meta, text, image }: { name: string; href?: string; meta?: string; text?: string; image?: string }) { const [mobileOpen, setMobileOpen] = useState(false); const ref = refFor(name); if (!ref && !text) return <>{name}</>; const resolved = { name, href: href ?? ref?.href ?? "#", meta: meta ?? ref?.meta ?? "机制说明", text: text ?? ref?.text ?? "", image: image ?? ref?.image }; const imageSrc = resolved.image ? `./vinerva/${resolved.image}` : undefined; return <><a className="cross-reference" href={resolved.href} onClick={(e) => { if (window.matchMedia("(hover: none), (pointer: coarse)").matches) { e.preventDefault(); setMobileOpen(true); } }}><span className="cross-label">{name}</span><span className="cross-popover" role="tooltip">{imageSrc && <span className="cross-image"><Image src={imageSrc} alt="" fill sizes="72px" /></span>}<span className="cross-copy"><small>{resolved.meta}</small><b>{resolved.name}</b><span>{resolved.text}</span><em>点击跳转至详情</em></span></span></a><MobileReferenceDialog open={mobileOpen} onClose={() => setMobileOpen(false)} name={resolved.name} meta={resolved.meta} text={resolved.text} href={resolved.href} imageSrc={imageSrc} /></>; }
function RichText({ text, exclude }: { text: string; exclude?: string }) { const names = referenceNames.filter((x) => x !== exclude); const escaped = names.map((x) => x.replace(/[-/\^$*+?.()|[\]{}]/g, "\\$&")); const parts = escaped.length ? text.split(new RegExp(`(${escaped.join("|")})`, "g")) : [text]; return <>{parts.map((part, i) => names.includes(part) ? <CrossReference name={part} key={`${part}-${i}`} /> : part)}</>; }
function ExpandableRow({ entryId, name, seal, cost, image, baseGame = false, open, onToggle, children }: { entryId: string; name: string; seal?: number; cost?: number | string; image?: string; baseGame?: boolean; open: boolean; onToggle: (id: string) => void; children: ReactNode }) { return <article className={`expandable-row ${baseGame ? "base-game-entry" : ""} ${open ? "is-open" : ""}`} id={entryId}><button className="expandable-summary" type="button" onClick={() => onToggle(entryId)} aria-expanded={open}>{seal !== undefined && <span className="summary-seal">{seal}</span>}{image && <span className="summary-image"><Image src={`./vinerva/${image}`} alt="" fill sizes="56px" /></span>}<span className="summary-name">{name}</span><ChevronDown className="summary-chevron" size={16} />{cost !== undefined && <span className="summary-cost"><small>消耗</small>{cost}</span>}</button><div className="expandable-content"><div className="expandable-inner">{children}</div></div></article>; }
const relations: Record<string, { sources?: Relation[]; effects?: Relation[] }> = {
  "Vinerva's Gift": { sources: [{ name: "Harvest for Gold", href: "#entry-harvest-for-gold" }, { name: "Harvest Nectar", href: "#entry-harvest-nectar" }, { name: "Drink Peace Lily", href: "#entry-drink-peace-lily" }, { name: "Use Leper's Succor", href: "#entry-use-leper-s-succor" }], effects: [{ name: "Black Forest", href: "#entry-black-forest" }, { name: "Neurotoxins", href: "#entry-neurotoxins" }, { name: "Manifestation", href: "#entry-manifestation" }] },
  "Heart of the Forest": { sources: [{ name: "Heart of the Forest", href: "#entry-heart-of-the-forest", meta: "封印 0 · 神力" }], effects: [{ name: "Harvest Seed", href: "#entry-harvest-seed" }] },
  "Vinerva Seed": { sources: [{ name: "Harvest Seed", href: "#entry-harvest-seed" }], effects: [{ name: "Heart of the Forest", href: "#entry-heart-of-the-forest" }] },
  "Vinerva's Gift of Might": { sources: [{ name: "Gift of Might", href: "#entry-gift-of-might" }], effects: [{ name: "Gift of Might", href: "#entry-gift-of-might" }] },
  "Wilderness Spirit": { sources: [{ name: "Wilderness Spirits", href: "#entry-wilderness-spirits" }] },
  "Vinerva Gift Accepted": { sources: [{ name: "Vinerva's Gift", href: "#entry-vinerva-s-gift" }] },
};
const powerEffects: Record<string, Relation[]> = { "Heart of the Forest": [{ name: "Heart of the Forest", href: "#entry-heart-location", meta: "地点与设施" }], "Grove of Golden Roses": [{ name: "Temptation of Gold", href: "#entry-temptation-of-gold", meta: "地点修正" }, { name: "Harvest for Gold", href: "#entry-harvest-for-gold", meta: "统治者行动" }], "Grove of Salvation": [{ name: "Temptation of Salvation", href: "#entry-temptation-of-salvation", meta: "地点修正" }, { name: "Gift of Salvation", href: "#entry-gift-of-salvation", meta: "英雄任务" }], "Grove of Nectar": [{ name: "Temptation of Nectar", href: "#entry-temptation-of-nectar", meta: "地点修正" }, { name: "Harvest Nectar", href: "#entry-harvest-nectar", meta: "统治者行动" }], "Grove of Peace Lillies": [{ name: "Temptation of Peace", href: "#entry-temptation-of-peace", meta: "地点修正" }, { name: "Drink Peace Lily", href: "#entry-drink-peace-lily", meta: "统治者行动" }], "Choking Spores": [{ name: "Choking Spores", href: "#entry-choking-spores-modifier", meta: "地点修正" }], "Grove of Leper's Succor": [{ name: "Temptation of Health", href: "#entry-temptation-of-health", meta: "地点修正" }, { name: "Use Leper's Succor", href: "#entry-use-leper-s-succor", meta: "统治者行动" }], "Grove of Dragonflower": [{ name: "Temptation of Might", href: "#entry-temptation-of-might", meta: "地点修正" }, { name: "Gift of Might", href: "#entry-gift-of-might", meta: "英雄任务" }], "Black Forest": [{ name: "Vinerva's Gift", href: "#entry-vinerva-s-gift", meta: "地点修正" }], "Neurotoxins": [{ name: "Vinerva's Gift", href: "#entry-vinerva-s-gift", meta: "地点修正" }], "Pheromones": [{ name: "Tempting Pheromones", href: "#entry-tempting-pheromones", meta: "地点修正" }], "Serpentine Vines": [{ name: "Challenge Danger", href: "#loop", meta: "本体挑战危险" }], "Manifestation": [{ name: "Manifestation", href: "#entry-manifestation-location", meta: "地点与设施" }], "Wilderness Spirits": [{ name: "Wilderness Spirit", href: "#entry-wilderness-spirit", meta: "特殊单位" }] };
function RelationGroup({ title, items }: { title: string; items?: Relation[] }) { if (!items?.length) return null; return <div className="relation-group"><b>{title}</b><div>{items.map((item) => <CrossReference key={`${title}-${item.href}`} {...item} />)}</div></div>; }
function DetailGrid({ items: rows, openEntries, onToggle, media = true }: { items: DetailItem[]; openEntries: Set<string>; onToggle: (id: string) => void; media?: boolean }) { return <div className="expandable-table">{rows.map((item) => { const id = item.id ? `entry-${item.id}` : anchorFor(item.name); const rel = relations[item.name]; return <ExpandableRow key={id} entryId={id} name={item.name} seal={item.seal} image={media ? item.image : undefined} baseGame={item.baseGame} open={openEntries.has(id)} onToggle={onToggle}>{item.meta && <div className="expanded-meta">{item.meta}</div>}{item.location && <div className="task-location"><b>执行地点</b><RichText text={item.location} exclude={item.name} /></div>}{item.statLine && <div className="task-stat-line">{item.statLine}</div>}<p><RichText text={item.text} exclude={item.name} /></p>{item.preferenceText && <div className="preference-note"><b>执行倾向</b><p><RichText text={item.preferenceText} exclude={item.name} /></p></div>}<RelationGroup title="来源" items={rel?.sources} /><RelationGroup title="造成的效果" items={rel?.effects} /></ExpandableRow>; })}</div>; }
function RecordSection({ id, index, title, children }: { id: string; index: string; title: string; children: ReactNode }) { return <section id={id} className="section records-section"><div className="plain-heading"><p className="section-index">{index} / {title}</p><h2>{title}</h2></div>{children}</section>; }

export default function VinervaArchive({ onGodChange }: { onGodChange: (god: GodChoice) => void }) {
  const root = useRef<HTMLElement>(null); const [sidebarHidden, setSidebarHidden] = useState(false); const [openEntries, setOpenEntries] = useState<Set<string>>(new Set());
  const allIds = [...powers.map((p) => anchorFor(p.name)), ...allDetails.map((d) => d.id ? `entry-${d.id}` : anchorFor(d.name))];
  const toggleEntry = (id: string) => setOpenEntries((current) => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; });
  useGSAP(() => { if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return; gsap.from(".hero-line", { yPercent: 115, duration: 1.05, ease: "power4.out" }); gsap.from(".hero-portrait", { scale: 1.06, opacity: 0, duration: 1.35, ease: "power3.out" }); gsap.utils.toArray<HTMLElement>(".reveal-image").forEach((element) => gsap.fromTo(element, { scale: 1.08, opacity: .2 }, { scale: 1, opacity: 1, ease: "none", scrollTrigger: { trigger: element, start: "top 92%", end: "bottom 58%", scrub: .8 } })); }, { scope: root });
  const nav = [["00", "top", "概览"], ["01", "loop", "基础信息与核心玩法"], ["02", "seals", "封印与 Agent 上限"], ["03", "powers", "神力"], ["04", "traits", "人物特质"], ["05", "location-modifiers", "地点修正"], ["06", "locations", "地点与设施"], ["07", "items", "物品"], ["08", "challenges", "挑战"], ["09", "hero-tasks", "英雄任务"], ["10", "ruler-actions", "统治者行动"], ["11", "religion", "宗教与教义"], ["12", "religious-tasks", "宗教任务"], ["13", "events", "事件"]];
  return <main ref={root} className={`site-shell vinerva-theme ${sidebarHidden ? "sidebar-hidden" : ""}`} onClickCapture={(event) => { const anchor = (event.target as HTMLElement).closest('a[href^="#entry-"]'); if (anchor) setOpenEntries((current) => new Set(current).add(anchor.getAttribute("href")!.slice(1))); }}><aside className="sidebar"><div className="sidebar-head"><div className="sidebar-brand god-switcher"><span className="brand-mark"><GodMark god="vinerva" /></span><label><select value="vinerva" onChange={(event) => onGodChange(event.target.value as GodChoice)} aria-label="切换神祇"><option value="she-who-will-feast">SHE WHO WILL FEAST</option><option value="iastur">IASTUR</option><option value="vinerva">VINERVA</option><option value="ophanim">OPHANIM</option><option value="mammon">MAMMON</option><option value="broken-maker">THE BROKEN MAKER</option><option value="evil-beneath">THE EVIL BENEATH</option><option value="deaths-games">DEATH'S GAMES</option><option value="cordyceps">CORDYCEPS</option><option value="kishi">KISHI</option><option value="living-void">LIVING VOID</option><option value="chandalor">CHANDALOR</option></select><small>神祇资料库</small></label></div><button className="sidebar-toggle" type="button" onClick={() => setSidebarHidden((value) => !value)} aria-label={sidebarHidden ? "展开侧边栏" : "暂时隐藏侧边栏"} title={sidebarHidden ? "展开侧边栏" : "暂时隐藏侧边栏"}>{sidebarHidden ? <PanelLeftOpen size={17} /> : <PanelLeftClose size={17} />}</button></div><button className="sidebar-index-link" type="button" onClick={() => onGodChange("index")}>← 返回神祇索引</button><nav className="sidebar-nav" aria-label="页面目录">{nav.map(([index, id, label]) => <a href={`#${id}`} key={id}><span>{index}</span><b>{label}</b></a>)}</nav><div className="sidebar-bulk"><button type="button" onClick={() => setOpenEntries(new Set(allIds))}>全部展开</button><button type="button" onClick={() => setOpenEntries(new Set())}>全部收起</button></div><p className="sidebar-note">悬浮带下划线的名称可查看说明，点击可跳转至详情。</p></aside><div className="content-shell">
    <header id="top" className="hero"><div className="hero-backdrop"><Image src="./vinerva/background.png" alt="" fill priority sizes="100vw" /></div><div className="hero-copy"><p className="eyebrow"><span>神祇档案 03</span><span>Base Game Elder God</span></p><div className="hero-title-wrap"><h1><span className="title-mask"><span className="hero-line">Vinerva, the Dark Goddess</span></span></h1></div><div className="hero-facts"><div><b>420</b><span>回合苏醒</span></div><div><b>5</b><span>最终 Agent 上限</span></div><div><b>50%</b><span>苏醒时世界恐慌</span></div></div></div><div className="hero-art"><div className="portrait-frame hero-portrait reveal-image"><Image src="./vinerva/portrait.png" alt="Vinerva 神祇立绘" fill priority sizes="(max-width: 900px) 100vw, 46vw" /></div></div></header>
    <section id="loop" className="section overview-section"><div className="section-heading"><p className="section-index">01 / 基础信息与核心玩法</p><h2>基础信息与核心玩法</h2></div><div className="overview-layout"><article className="overview-main"><h3>核心玩法</h3><ol className="core-sequence"><li><span>01</span><p>用 <CrossReference name="Heart of the Forest" /> 建立据点与根系网络，保证其他神力始终在 3 格范围内有施放中心。</p></li><li><span>02</span><p>先放置 <CrossReference name="Grove of Golden Roses" />、<CrossReference name="Grove of Nectar" />、<CrossReference name="Grove of Peace Lillies" /> 或 <CrossReference name="Grove of Leper's Succor" />，向人类提供解决问题的礼物。</p></li><li><span>03</span><p>等统治者执行对应行动，累积 <CrossReference name="Vinerva's Gift" />；英雄则会被 <CrossReference name="Gift of Salvation" /> 和 <CrossReference name="Gift of Might" /> 任务吸引。</p></li><li><span>04</span><p>用 <CrossReference name="Black Forest" />、<CrossReference name="Neurotoxins" /> 和 <CrossReference name="Choking Spores" /> 把礼物转成 Shadow、Madness 和经济衰败；用 <CrossReference name="Pheromones" /> 提高接受意愿。</p></li><li><span>05</span><p>用 <CrossReference name="Vinerva Seed" /> 让 Agent 迁移根系，或把高 Gift 的聚居地转化为 <CrossReference name="Manifestation" />，取得额外胜利分。</p></li><li><span>06</span><p>最后用 <CrossReference name="Wilderness Spirits" /> 制造不可控制的自然军势，清理剩余的人类据点。</p></li></ol><div className="overview-subsection"><h3>诱惑与毁灭</h3><p>Vinerva 不靠一次性爆发取胜：先用粮食、治病、安抚和财富解除人类眼前的问题，让统治者主动把灵魂交给馈赠；再把已接受的地点转成 Shadow、Madness 或 Manifestation。每一次善意的表象都会增加后续可利用的 Gift，但过早把人类养得太强，也会让最终清理更难。</p></div></article><aside className="basic-facts"><h3>基础信息</h3><dl><div><dt>封印解锁方式</dt><dd>常规回合解锁</dd></div><div><dt>最大回合数</dt><dd>常规 500 回合</dd></div><div><dt>苏醒回合</dt><dd>第 420 回合</dd></div><div><dt>苏醒时世界恐慌</dt><dd>50%</dd></div><div><dt>Agent 上限</dt><dd>初始 2，最终 5</dd></div><div><dt>初始 Agent</dt><dd>没有初始 Agent</dd></div></dl><div className="special-victory"><h3>特殊胜利</h3><p>无</p></div></aside></div></section>
    <section id="seals" className="section seals-section"><div className="section-heading row-heading"><div><p className="section-index">02 / 封印进度</p><h2>封印、解锁回合与 Agent 上限</h2></div></div><div className="seal-table"><div className="seal-head"><span>封印</span><span>回合</span><span>Agent</span><span>神力/恢复</span><span>本阶段内容</span></div>{seals.map((item) => <div className="seal-row" key={item.seal}><span className="seal-number">{item.seal}</span><span className="turn">{item.turn}</span><span className="agent-count">{item.agents}</span><span className="power-gain">{`${item.seal + 1} / ${(0.035 * (item.seal + 1)).toFixed(3)}`}</span><span className="seal-reward">{item.reward ? item.reward.split("、").map((reward, index) => <span className="seal-reference-item" key={reward}>{reward === "苏醒" ? reward : <CrossReference name={reward} />}{index < item.reward.split("、").length - 1 && <i>、</i>}</span>) : null}</span></div>)}</div><div className="seal-formula"><b>神力恢复公式</b><code>0.035 ×（已破封印数 + 1）× 难度缩放</code><span>表中按难度缩放为 1 计算；Heart of the Forest 的消耗另行按使用次数增长。</span></div></section>
    <section id="powers" className="section powers-section records-section"><div className="powers-intro plain-heading"><p className="section-index">03 / 神力</p><h2>神力</h2><div className="power-legend"><span><Eye size={16} />效果</span><span><Shield size={16} />限制</span></div></div><div className="expandable-table powers-table">{powers.map((power) => { const id = anchorFor(power.name); return <ExpandableRow key={id} entryId={id} name={power.name} seal={power.seal} cost={power.cost} image={power.icon} open={openEntries.has(id)} onToggle={toggleEntry}><div className="expanded-section"><h4>具体效果</h4><p><RichText text={power.effect} exclude={power.name} /></p></div><div className="expanded-section"><h4>释放限制</h4><p><RichText text={power.limit} exclude={power.name} /></p></div><RelationGroup title="造成的效果" items={powerEffects[power.name]} /></ExpandableRow>; })}</div></section>
    <RecordSection id="traits" index="04" title="人物特质"><DetailGrid items={traits} openEntries={openEntries} onToggle={toggleEntry} /></RecordSection>
    <RecordSection id="location-modifiers" index="05" title="地点修正"><DetailGrid items={locationModifiers} openEntries={openEntries} onToggle={toggleEntry} /></RecordSection>
    <RecordSection id="locations" index="06" title="地点与设施"><DetailGrid items={locations} openEntries={openEntries} onToggle={toggleEntry} /></RecordSection>
    <RecordSection id="items" index="07" title="物品"><DetailGrid items={items} openEntries={openEntries} onToggle={toggleEntry} /></RecordSection>
    <RecordSection id="challenges" index="08" title="挑战"><DetailGrid items={challenges} openEntries={openEntries} onToggle={toggleEntry} /></RecordSection>
    <RecordSection id="hero-tasks" index="09" title="英雄任务"><DetailGrid items={heroTasks} openEntries={openEntries} onToggle={toggleEntry} /></RecordSection>
    <RecordSection id="ruler-actions" index="10" title="统治者行动"><DetailGrid items={rulerActions} openEntries={openEntries} onToggle={toggleEntry} /></RecordSection>
    <RecordSection id="religion" index="11" title="宗教与教义"><DetailGrid items={religion} openEntries={openEntries} onToggle={toggleEntry} /></RecordSection>
    <RecordSection id="religious-tasks" index="12" title="宗教任务"><DetailGrid items={religiousTasks} openEntries={openEntries} onToggle={toggleEntry} /></RecordSection>
    <RecordSection id="events" index="13" title="事件"><DetailGrid items={events} openEntries={openEntries} onToggle={toggleEntry} /></RecordSection>
    <footer><div><CircleDot size={20} />Vinerva</div><p>基于游戏本体程序集、事件定义与原始美术素材整理。</p><span>Shadows of Forbidden Gods · God Archive</span></footer>
  </div></main>;
}